'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['math','geometry','model','csg','exchange','production','kernel','constraints'])require('../src/'+f+'.js');
const K=globalThis.Kestrel,C=K.Constraints,E=K.Expressions,{V,M}=K.Math,results=[];
function test(name,fn){try{fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e);}}
function near(a,b,t=1e-5){assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);}
function fresh(){const d=new K.Drawing('Constraint test');d.currentLayer=d.layers[0].id;return d;}
const line=(d,a,b)=>d.add('LINE',{points:[a.length===2?[...a,0]:a,b.length===2?[...b,0]:b]});
const circle=(d,p,r)=>d.add('CIRCLE',{center:[...p,0],radius:r});
const point=(d,p)=>d.add('POINT',{position:p.length===2?[...p,0]:p});
const ref=(e,p,segment)=>({entity:e.id,...(p!=null?{point:p}:{}),...(segment!=null?{segment}:{})});
const add=(d,type,a,b,value,extra={})=>C.add(d,{type,a,...(b?{b}:{}),...(value!=null?{value}:{}),...extra});
function freeze(d,e){add(d,'fix-entity',ref(e));}
function delta(e){return V.sub(e.points[1],e.points[0]);}
function rectangle(){const d=fresh(),e=d.add('POLYLINE',{points:[[0,0,0],[100,0,0],[100,60,0],[0,60,0]],closed:true}),s=C.state(d,true);s.parameters=[{name:'Width',expression:'100'},{name:'Height',expression:'Width * .6'}];add(d,'fixed',ref(e,0));for(let i=0;i<4;i++)add(d,i%2?'vertical':'horizontal',ref(e,0,i));add(d,'distance-x',ref(e,0),ref(e,1),'Width');add(d,'distance-y',ref(e,0),ref(e,3),'Height');return{d,e,s};}
test('expression precedence, scientific notation and right-associative powers',()=>{near(E.evaluate('-2^2 + 2^3^2'),508);near(E.evaluate('1.25e2 / (3 + 2)'),25);near(E.evaluate('.5^-2'),4);});
test('whitelisted math functions and degree constant',()=>{near(E.evaluate('sin(30*deg)+cos(60*deg)'),1);near(E.evaluate('hypot(3,4)+sqrt(9)'),8);near(E.evaluate('atan2(1,0)/deg'),90);});
test('named parameters evaluate a dependency graph independent of ordering',()=>{const p=E.parameters([{name:'Height',expression:'Width/2'},{name:'Width',expression:'25.4*2'}]);near(p.get('Height'),25.4);});
for(const code of ['globalThis.alert(1)','constructor.constructor(1)','2;3','1/0','sqrt(-1)','pow(2)','sin()','x','2 +','2 ** 3','1e999'])test('reject unsafe or invalid expression '+code,()=>assert.throws(()=>E.evaluate(code)));
test('parameter cycles and missing dependencies reject',()=>{assert.throws(()=>E.parameters([{name:'A',expression:'B+1'},{name:'B',expression:'A-1'}]),/cycle/);assert.throws(()=>E.parameters([{name:'A',expression:'Missing'}]),/Unknown/);});
test('parameter name pollution and duplicates reject',()=>{for(const name of ['__proto__','constructor','sin','pi','a.b'])assert.throws(()=>E.parameters([{name,expression:'1'}]));assert.throws(()=>E.parameters([{name:'A',expression:'1'},{name:'A',expression:'2'}]));});
test('complex expressions have bounded token and nesting counts',()=>{assert.throws(()=>E.evaluate('('.repeat(50)+'1'+')'.repeat(50)),/nesting/);assert.throws(()=>E.evaluate('1+'.repeat(200)+'1'),/complex/);});
test('horizontal line changes actual endpoints',()=>{const d=fresh(),e=line(d,[0,0],[10,2]);add(d,'horizontal',ref(e));near(e.points[0][1],e.points[1][1]);assert.equal(d.constraintReport.degreesOfFreedom,3);});
test('vertical line changes actual endpoints',()=>{const d=fresh(),e=line(d,[0,0],[2,10]);add(d,'vertical',ref(e));near(e.points[0][0],e.points[1][0]);});
test('coincident endpoints are solved together',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[11,2],[20,5]);add(d,'coincident',ref(a,'end'),ref(b,'start'));near(V.dist(a.points[1],b.points[0]),0);});
test('fixed point, horizontal and length fully constrain a line',()=>{const d=fresh(),e=line(d,[1,2],[11,3]);add(d,'fixed',ref(e,'start'));add(d,'horizontal',ref(e));add(d,'distance',ref(e,'start'),ref(e,'end'),20);near(V.dist(...e.points),20);near(e.points[0][0],1);near(e.points[0][1],2);assert.equal(d.constraintReport.degreesOfFreedom,0);});
test('fixed entity preserves all segment coordinates',()=>{const d=fresh(),e=line(d,[1,2],[11,5]);freeze(d,e);d.transaction('attempt drag',()=>{e.points[1]=[40,50,0];});near(e.points[1][0],11);near(e.points[1][1],5);});
test('signed horizontal and vertical distances constrain endpoint direction',()=>{const d=fresh(),e=line(d,[0,0],[4,5]);add(d,'fixed',ref(e,0));add(d,'distance-x',ref(e,0),ref(e,1),-10);add(d,'distance-y',ref(e,0),ref(e,1),20);near(e.points[1][0],-10);near(e.points[1][1],20);});
test('parallel relation keeps a fixed reference line',()=>{const d=fresh(),a=line(d,[0,0],[10,2]),b=line(d,[0,10],[8,15]);freeze(d,a);add(d,'parallel',ref(a),ref(b));near(V.len(V.cross(V.norm(delta(a)),V.norm(delta(b)))),0);});
test('perpendicular relation rotates geometry',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[2,5],[5,15]);freeze(d,a);add(d,'perpendicular',ref(a),ref(b));near(V.dot(V.norm(delta(a)),V.norm(delta(b))),0);});
test('collinear relation aligns position and orientation',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[12,4],[20,6]);freeze(d,a);add(d,'collinear',ref(a),ref(b));near(b.points[0][1],0);near(b.points[1][1],0);});
test('equal line lengths maintain fixed reference length',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[12,4],[20,6]);freeze(d,a);add(d,'equal',ref(a),ref(b));near(V.dist(...b.points),10);});
test('equal circle radii are independent of center location',()=>{const d=fresh(),a=circle(d,[0,0],5),b=circle(d,[20,0],7);freeze(d,a);add(d,'equal',ref(a),ref(b));near(b.radius,5);near(b.center[0],20);});
test('concentric circles share centers without forcing equal radii',()=>{const d=fresh(),a=circle(d,[0,0],5),b=circle(d,[2,3],7);freeze(d,a);add(d,'concentric',ref(a),ref(b));near(V.dist(a.center,b.center),0);near(b.radius,7);});
test('radius and diameter constraints are distinct',()=>{const d=fresh(),a=circle(d,[0,0],5),b=circle(d,[20,0],7);add(d,'radius',ref(a),null,8);add(d,'diameter',ref(b),null,30);near(a.radius,8);near(b.radius,15);});
test('angle relation uses signed degrees',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[0,0],[10,8]);freeze(d,a);add(d,'angle',ref(a),ref(b),60);const v=delta(b);near(Math.atan2(v[1],v[0])*180/Math.PI,60);});
test('point on line projects the point onto a fixed infinite line',()=>{const d=fresh(),a=point(d,[3,5]),b=line(d,[0,0],[10,0]);freeze(d,b);add(d,'point-on-line',ref(a,'position'),ref(b));near(a.position[1],0);near(a.position[0],3);});
test('point on circle uses true analytical radius',()=>{const d=fresh(),a=point(d,[3,5]),b=circle(d,[0,0],10);freeze(d,b);add(d,'point-on-circle',ref(a,'position'),ref(b));near(V.dist(a.position,b.center),10);});
test('midpoint relation fixes a point to a segment midpoint',()=>{const d=fresh(),a=point(d,[3,5]),b=line(d,[2,4],[12,6]);freeze(d,b);add(d,'midpoint',ref(a,'position'),ref(b));near(a.position[0],7);near(a.position[1],5);});
test('symmetry reflects a point across a fixed axis',()=>{const d=fresh(),a=point(d,[2,3]),b=point(d,[-4,2]),axis=line(d,[0,-10],[0,10]);freeze(d,a);freeze(d,axis);add(d,'symmetric',ref(a,'position'),ref(b,'position'),null,{c:ref(axis)});near(b.position[0],-2);near(b.position[1],3);});
test('line-circle tangency changes a center with fixed radius',()=>{const d=fresh(),a=line(d,[-20,0],[20,0]),b=circle(d,[2,8],3);freeze(d,a);add(d,'radius',ref(b),null,3);add(d,'tangent',ref(a),ref(b));near(Math.abs(b.center[1]),3);});
test('external circle-circle tangency uses sum of radii',()=>{const d=fresh(),a=circle(d,[0,0],5),b=circle(d,[15,2],3);freeze(d,a);add(d,'radius',ref(b),null,3);add(d,'tangent',ref(a),ref(b));near(V.dist(a.center,b.center),8);});
test('internal circle-circle tangency uses difference of radii',()=>{const d=fresh(),a=circle(d,[0,0],10),b=circle(d,[5,2],3);freeze(d,a);add(d,'radius',ref(b),null,3);add(d,'tangent',ref(a),ref(b),null,{internal:true});near(V.dist(a.center,b.center),7);});
test('arc radius and fixed center leave two endpoint angle degrees of freedom',()=>{const d=fresh(),a=d.add('ARC',{center:[0,0,0],radius:10,startAngle:0,endAngle:Math.PI/2});add(d,'fixed',ref(a,'center'));add(d,'radius',ref(a),null,20);near(a.radius,20);assert.equal(d.constraintReport.degreesOfFreedom,2);});
test('arc endpoint and midpoint references use circular geometry',()=>{const d=fresh(),a=d.add('ARC',{center:[0,0,0],radius:10,startAngle:0,endAngle:Math.PI/2}),p=point(d,[8,7]);freeze(d,a);add(d,'coincident',ref(p,'position'),ref(a,'mid'));near(V.dist(p.position,K.Geo.conicPoint(a,Math.PI/4)),0);});
test('rectangle is fully constrained with dependent dimensions',()=>{const {d,e,s}=rectangle();assert.equal(d.constraintReport.degreesOfFreedom,0);d.transaction('Resize',()=>{s.parameters[0].expression='150';});near(e.points[1][0],150);near(e.points[2][1],90);});
test('parameter edits update linked hatch and dimension after solving',()=>{const {d,e,s}=rectangle();const dim=d.add('DIMENSION',{kind:'linear',measureAxis:[1,0,0],points:[e.points[0],e.points[1]],offset:10,anchors:[0,1].map(index=>({entity:e.id,kind:'point',index}))}),h=d.add('HATCH',{points:K.clone(e.points),loops:[K.clone(e.points)],boundaryIds:[e.id],pattern:'solid'});d.reindex();d.transaction('Resize',()=>{s.parameters[0].expression='200';});near(dim.points[1][0],200);near(h.loops[0][2][1],120);});
test('undo and redo restore both equations and solved geometry',()=>{const {d,s}=rectangle(),before=d.snapshot();d.transaction('Resize',()=>{s.parameters[0].expression='200';});d.undo();assert.equal(d.snapshot(),before);d.redo();near(d.entities[0].points[1][0],200);});
test('conflicting distance edit rolls back equations, coordinates and history',()=>{const {d,e}=rectangle(),before=d.snapshot(),n=d.undoStack.length;assert.throws(()=>add(d,'distance-x',ref(e,0),ref(e,1),200),/rolled back/);assert.equal(d.snapshot(),before);assert.equal(d.undoStack.length,n);});
test('failed parameter dependency edit rolls back atomically',()=>{const {d,s}=rectangle(),before=d.snapshot();assert.throws(()=>d.transaction('cycle',()=>{s.parameters[0].expression='Height';}),/cycle/);assert.equal(d.snapshot(),before);});
test('redundant but consistent equations report redundancy',()=>{const d=fresh(),a=line(d,[0,0],[10,0]);add(d,'horizontal',ref(a));add(d,'horizontal',ref(a));assert.equal(d.constraintReport.redundantEquations,1);assert.equal(d.constraintReport.degreesOfFreedom,3);});
test('locked layer geometry is constant during solving',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[0,4],[10,8]);const l=d.addLayer('Fixed','#ffffff');a.layer=l.id;l.locked=true;d.reindex();add(d,'parallel',ref(a),ref(b));near(a.points[1][0],10);near(a.points[1][1],0);near(delta(b)[1],0);assert.equal(d.constraintReport.variables,4);});
test('inconsistent constraints on a locked line fail without modifying it',()=>{const d=fresh(),a=line(d,[0,0],[10,5]);d.layer(a).locked=true;const before=d.snapshot();assert.throws(()=>add(d,'horizontal',ref(a)),/rolled back/);assert.equal(d.snapshot(),before);});
test('suppressed constraints no longer drive geometry',()=>{const {d,e,s}=rectangle();d.transaction('suppress width',()=>{s.constraints.find(c=>c.type==='distance-x').suppressed=true;e.points[1][0]=180;e.points[2][0]=180;});near(e.points[1][0],180);assert.equal(d.constraintReport.degreesOfFreedom,1);});
test('disabled solving retains equations while allowing free edits',()=>{const {d,e,s}=rectangle();d.transaction('disable',()=>{s.enabled=false;});d.transaction('edit',()=>{e.points[1][0]=222;});near(e.points[1][0],222);d.transaction('enable',()=>{s.enabled=true;});near(e.points[1][0],100);});
test('deleting geometry prunes its constraints and undo restores them',()=>{const {d,e,s}=rectangle(),count=s.constraints.length;d.transaction('delete',()=>d.remove([e.id]));assert.equal(C.state(d).constraints.length,0);d.undo();assert.equal(C.state(d).constraints.length,count);});
test('native project round trip retains constraint definitions and parameter units',()=>{const {d}=rectangle();assert.deepEqual(K.Drawing.from(d.serialize()).serialize(),d.serialize());});
test('physical unit conversion scales geometry and fixed targets but keeps parameter units explicit',()=>{const {d}=rectangle();d.transaction('mm to cm',()=>{C.convertUnits(d,'cm',.1,true);d.entities=d.entities.map(e=>K.Geo.transform(e,M.scale(.1)));d.units='cm';});near(d.entities[0].points[1][0],10);near(d.entities[0].points[2][1],6);assert.equal(C.state(d).units,'mm');});
test('metadata-only unit change preserves numerical parameter meaning',()=>{const {d}=rectangle();d.transaction('metadata units',()=>{C.convertUnits(d,'cm',1,false);d.units='cm';});near(d.entities[0].points[1][0],100);assert.equal(C.state(d).units,'cm');});
test('saved tilted sketch plane solves in local XY without flattening world Z',()=>{const d=fresh();d.production.ucs={origin:[10,20,30],x:[0,1,0],y:[0,0,1]};const a=line(d,[10,20,30],[10,30,32]);add(d,'fixed',ref(a,0));add(d,'horizontal',ref(a));add(d,'distance',ref(a,0),ref(a,1),20);near(a.points[1][0],10);near(a.points[1][1],40);near(a.points[1][2],30);});
test('off-plane geometry rejects with atomic rollback',()=>{const d=fresh(),a=line(d,[0,0,0],[10,2,3]),before=d.snapshot();assert.throws(()=>add(d,'horizontal',ref(a)),/plane/);assert.equal(d.snapshot(),before);});
test('bulged polyline is rejected rather than silently straightened',()=>{const d=fresh(),a=d.add('POLYLINE',{points:[[0,0,0],[10,0,0]],bulges:[1,0]}),before=d.snapshot();assert.throws(()=>add(d,'horizontal',ref(a)),/bulged/);assert.equal(d.snapshot(),before);});
test('noncircular conic axes reject without losing shape',()=>{const d=fresh(),a=d.add('CIRCLE',{center:[0,0,0],radius:10,axisX:[10,0,0],axisY:[0,5,0]});assert.throws(()=>add(d,'radius',ref(a),null,8),/circular/);});
test('nonpositive dimensions reject without changing geometry',()=>{const d=fresh(),a=circle(d,[0,0],10);for(const v of [0,-1])assert.throws(()=>add(d,'radius',ref(a),null,v),/positive/);near(d.entities[0].radius,10);});
test('missing entity and bad segment references reject on load',()=>{const {d}=rectangle(),p=d.serialize();p.production.parametric.constraints[0].a.entity='missing';assert.throws(()=>K.Drawing.from(p),/missing entity/);const q=d.serialize();q.production.parametric.constraints[1].a.segment=99;assert.throws(()=>K.Drawing.from(q),/segment/);});
test('bounded variable count rejects oversized sketches',()=>{const d=fresh(),a=d.add('POLYLINE',{points:Array.from({length:100},(_,i)=>[i,0,0])});assert.throws(()=>add(d,'horizontal',ref(a)),/160 scalar/);});
test('bounded reference geometry rejects huge polylines before matrix allocation',()=>{const d=fresh(),a=d.add('POLYLINE',{points:Array.from({length:1000},(_,i)=>[i,0,0])});assert.throws(()=>add(d,'horizontal',ref(a)),/512 scalars/);});
test('diagnostic solve without applying leaves source coordinates unchanged',()=>{const {d,s}=rectangle();s.parameters[0].expression='200';const before=JSON.stringify(d.entities),r=C.solve(d,{apply:false});assert.ok(r.converged);assert.equal(JSON.stringify(d.entities),before);});

test('positive distance from initially coincident points selects a finite solution branch',()=>{const d=fresh(),a=point(d,[0,0]),b=point(d,[0,0]);freeze(d,a);add(d,'distance',ref(a,'position'),ref(b,'position'),10);near(V.dist(a.position,b.position),10);});
function copied(source,dest,matrix){const ids=new Map();for(const e of source.entities){const copy=K.Geo.transform(e,matrix);copy.id=K.uid();dest.add(copy);ids.set(e.id,copy.id);}dest.reindex();const warnings=C.copyInto(dest,source.serialize(),ids,matrix);return{ids,warnings};}
test('clipboard transfer retains complete constrained sketch after translation',()=>{const {d}=rectangle(),out=fresh();out.transaction('copy',()=>{const {warnings}=copied(d,out,M.translation(500,100,0));assert.equal(warnings.length,0);});near(out.entities[0].points[0][0],500);near(out.entities[0].points[2][1],160);assert.equal(out.constraintReport.degreesOfFreedom,0);});
test('clipboard transfer preserves physical size across drawing units',()=>{const {d}=rectangle(),out=fresh();out.units='cm';out.transaction('copy',()=>copied(d,out,M.scale(.1)));near(out.entities[0].points[1][0],10);assert.equal(C.state(out).units,'mm');});
test('clipboard transfer renames colliding parameters and rewrites dependent expressions',()=>{const {d}=rectangle(),{d:out}=rectangle();out.transaction('copy',()=>copied(d,out,M.translation(300,0,0)));assert.equal(out.entities.length,2);assert.ok(C.state(out).parameters.some(r=>r.name==='Width_copy1'));out.transaction('resize copy',()=>{C.state(out).parameters.find(r=>r.name==='Width_copy1').expression='200';});near(out.entities[0].points[1][0],100);near(out.entities[1].points[1][0],500);near(out.entities[1].points[2][1],120);});
test('clipboard retains uniformly scaled equations without scaling angle expressions',()=>{const {d}=rectangle(),out=fresh();out.transaction('copy',()=>copied(d,out,M.scale(2)));near(out.entities[0].points[1][0],200);near(out.entities[0].points[2][1],120);});
test('clipboard warns when a different sketch plane prevents constraint transfer',()=>{const {d}=rectangle(),{d:out}=rectangle();out.transaction('copy',()=>{const {warnings}=copied(d,out,M.translation(0,0,20));assert.match(warnings[0],/plane/);});assert.equal(C.state(out).constraints.length,7);});
test('clipboard warns about omitted external constraint references',()=>{const d=fresh(),a=line(d,[0,0],[10,0]),b=line(d,[10,0],[20,0]);add(d,'coincident',ref(a,1),ref(b,0));const out=fresh(),copy=out.add({...K.clone(a),id:K.uid()}),warnings=C.copyInto(out,d.serialize(),new Map([[a.id,copy.id]]),M.identity());assert.match(warnings[0],/outside/);assert.equal(C.state(out),undefined);});
const failed=results.filter(r=>r.status==='failed').length;fs.mkdirSync(path.join(__dirname,'results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'results/constraints-results.json'),JSON.stringify({passed:results.length-failed,failed,tests:results},null,2)+'\n');console.log(`Constraints: ${results.length-failed}/${results.length} passed`);process.exitCode=failed?1:0;
