'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
for(const f of ['math','geometry','model','exchange','production','kernel','constraints','dynamic-blocks'])require('../src/'+f+'.js');
const K=globalThis.Kestrel,D=K.DynamicBlocks,P=K.Production,{M}=K.Math,results=[];
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const test=(name,fn)=>{try{fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e);}};
function fixture(actions=[],parameters=[{name:'Width',type:'length',default:100,min:10,max:1000}]){
 const doc=new K.Drawing('Dynamic test');doc.currentLayer='0';
 const b={id:'block',name:'Plate',entities:[{id:'line',type:'LINE',points:[[0,0,0],[100,0,0]],layer:'0',color:'byblock'},{id:'circle',type:'CIRCLE',center:[80,30,0],radius:5,layer:'0'}],attributes:[],dynamic:{version:1,parameters,actions}};
 doc.production.blocks.push(b);const e=doc.add('INSERT',{block:b.id,matrix:Array.from(M.identity()),parameters:{},attributes:{},color:'#ff0000'});doc.reindex();return {doc,b,e};
}
const output=(doc,e)=>P.expand(doc,doc.byId.get(e.id));
const move=()=>({type:'move',targets:['line'],x:'Width - 100'});
test('default values do not change definition geometry',()=>{const {doc,b,e}=fixture([move()]);near(output(doc,e)[0].points[0][0],0);near(b.entities[0].points[0][0],0);});
test('instance values regenerate geometry without mutation or cumulative drift',()=>{const {doc,b,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});near(output(doc,e)[0].points[0][0],100);D.setValues(doc,e.id,{Width:150});near(output(doc,e)[0].points[0][0],50);near(b.entities[0].points[0][0],0);});
test('different instances share actions but not parameter values',()=>{const {doc,b,e}=fixture([move()]);const other=P.insertBlock(doc,b.id,[300,0,0]);D.setValues(doc,e.id,{Width:200});near(output(doc,e)[0].points[0][0],100);near(output(doc,other)[0].points[0][0],300);});
test('native project round trip retains complete behavior',()=>{const {doc,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});const saved=doc.serialize(),again=K.Drawing.from(saved);assert.deepEqual(again.serialize(),saved);near(output(again,e)[0].points[0][0],100);});
test('parameter changes and reset participate in undo redo',()=>{const {doc,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});doc.undo();near(output(doc,e)[0].points[0][0],0);doc.redo();near(output(doc,e)[0].points[0][0],100);D.setValues(doc,e.id,{},true);near(output(doc,e)[0].points[0][0],0);doc.undo();near(output(doc,e)[0].points[0][0],100);});
test('failed edit restores parameters, geometry and undo stack',()=>{const {doc,e}=fixture([move()]);const before=doc.snapshot(),history=doc.undoStack.length;assert.throws(()=>D.setValues(doc,e.id,{Width:-1}));assert.equal(doc.snapshot(),before);assert.equal(doc.undoStack.length,history);});
test('locked instances cannot be changed indirectly',()=>{const {doc,e}=fixture([move()]);doc.layer('0').locked=true;assert.throws(()=>D.setValues(doc,e.id,{Width:200}),/editable/);});
test('shared definition action update invalidates rendered geometry',()=>{const {doc,b,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});near(doc.geometry(doc.byId.get(e.id)).segments[0][0][0],100);D.setDefinition(doc,b.id,{...b.dynamic,actions:[{...move(),x:'Width - 50'}]});near(doc.geometry(doc.byId.get(e.id)).segments[0][0][0],150);});
test('remove behavior cleans instance parameters atomically',()=>{const {doc,b,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});D.setDefinition(doc,b.id,null);assert.equal(doc.byId.get(e.id).parameters,undefined);doc.undo();near(output(doc,e)[0].points[0][0],100);});
test('stretch preserves the unselected endpoint',()=>{const {doc,e}=fixture([{type:'stretch',targets:['line'],min:[90,-1,-1],max:[110,1,1],x:'Width - 100'}]);D.setValues(doc,e.id,{Width:170});assert.deepEqual(output(doc,e)[0].points,[[0,0,0],[170,0,0]]);});
test('partial circle stretch rejects instead of deforming analytic geometry',()=>{const {doc,b}=fixture([{type:'stretch',targets:['circle'],min:[80,20,-1],max:[90,40,1],x:20}]);assert.throws(()=>D.setDefinition(doc,b.id,b.dynamic),/partially/);});
test('rotate action uses degree expression and pivot',()=>{const {doc,e}=fixture([{type:'rotate',targets:['line'],angle:90,center:[0,0,0]}]);near(output(doc,e)[0].points[1][0],0);near(output(doc,e)[0].points[1][1],100);});
test('scale action scales true circle radius and center',()=>{const {doc,e}=fixture([{type:'scale',targets:['circle'],factor:2,center:[80,30,0]}]);near(output(doc,e)[1].radius,10);assert.deepEqual(output(doc,e)[1].center,[80,30,0]);});
test('boolean flip reflects about its specified plane',()=>{const {doc,e}=fixture([{type:'flip',targets:['line'],parameter:'Mirror',normal:[1,0,0]}],[{name:'Mirror',type:'boolean',default:false}]);D.setValues(doc,e.id,{Mirror:true});near(output(doc,e)[0].points[1][0],-100);D.setValues(doc,e.id,{Mirror:false});near(output(doc,e)[0].points[1][0],100);});
test('array generates independent rows and columns',()=>{const {doc,e}=fixture([{type:'array',targets:['circle'],columns:3,rows:2,dx:20,dy:40}]);const rows=output(doc,e).filter(e=>e.type==='CIRCLE');assert.equal(rows.length,6);assert.deepEqual(rows.at(-1).center,[120,70,0]);assert.equal(new Set(rows.map(e=>e.id)).size,6);});
test('later actions act on array descendants using source identity',()=>{const {doc,e}=fixture([{type:'array',targets:['circle'],columns:2,dx:20},{type:'move',targets:['circle'],y:10}]);assert.ok(output(doc,e).filter(e=>e.type==='CIRCLE').every(e=>e.center[1]===40));});
test('visibility states control only their declared target scope',()=>{const {doc,e}=fixture([{type:'visibility',parameter:'State',targets:['line'],states:{Visible:['line'],Hidden:[]}}],[{name:'State',type:'enum',default:'Visible',values:['Visible','Hidden']}]);D.setValues(doc,e.id,{State:'Hidden'});assert.deepEqual(output(doc,e).map(e=>e.type),['CIRCLE']);});
test('lookup rows drive typed outputs and dependent expressions',()=>{const {doc,b,e}=fixture([{type:'scale',targets:['circle'],factor:'Diameter / 10'}],[{name:'Size',type:'enum',default:'S',values:['S','L']},{name:'Radius',type:'length',default:5},{name:'Diameter',type:'length',default:10,expression:'2 * Radius'}]);b.dynamic.lookups=[{parameter:'Size',rows:[{value:'S',set:{Radius:5}},{value:'L',set:{Radius:10}}]}];D.setValues(doc,e.id,{Size:'L'});near(output(doc,e)[1].radius,10);assert.throws(()=>D.setValues(doc,e.id,{Radius:3}),/driven/);});
test('expression graph resolves out of order',()=>{const {b}=fixture([],[{name:'B',type:'number',default:4,expression:'A * 2'},{name:'A',type:'number',default:2}]);near(D.resolve(b).values.B,4);});
test('expression cycles reject',()=>{const {b}=fixture([],[{name:'B',type:'number',default:4,expression:'A'},{name:'A',type:'number',default:2,expression:'B'}]);assert.throws(()=>D.resolve(b),/Cyclic/);});
test('length increments and discrete allowed values are enforced',()=>{const {b}=fixture([],[{name:'Width',type:'length',default:100,min:60,max:300,step:10}]);assert.throws(()=>D.resolve(b,{Width:105}),/increment/);near(D.resolve(b,{Width:110}).values.Width,110);b.dynamic.parameters[0].values=[100,200];assert.throws(()=>D.resolve(b,{Width:110}),/allowed/);});
test('attributes participate in actions and text interpolation',()=>{const {doc,b,e}=fixture([{type:'move',targets:['attribute:PART'],x:'Width - 100'}]);b.attributes=[{tag:'PART',value:'W=${Width}',position:[0,0,0],height:3}];D.setValues(doc,e.id,{Width:200});const t=output(doc,e).find(e=>e.attributeTag==='PART');assert.equal(t.text,'W=200');near(t.position[0],100);});
test('instance attribute text is interpolated without changing definition',()=>{const {doc,b,e}=fixture();b.attributes=[{tag:'PART',value:'Default',position:[0,0,0],height:3}];e.attributes.PART='Custom ${Width}';assert.equal(output(doc,e).find(e=>e.attributeTag).text,'Custom 100');assert.equal(b.attributes[0].value,'Default');});
test('ByBlock appearance inherits selected insert color',()=>{const {doc,e}=fixture();K.validateProject(doc.serialize());assert.equal(output(doc,e)[0].color,'#ff0000');});
test('nested dynamic references evaluate before their instance transform',()=>{const {doc,b,e}=fixture([move()]);const nested={id:'nested',name:'Nested',entities:[{id:'nestedInsert',type:'INSERT',block:b.id,matrix:Array.from(M.translation(300,0,0)),parameters:{Width:200},layer:'0'}]};doc.production.blocks.push(nested);e.block=nested.id;doc.reindex();near(output(doc,e)[0].points[0][0],400);});
test('ordinary transforms preserve independent parameter values',()=>{const {doc,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});doc.transaction('move',()=>doc.transform([e.id],M.translation(20,30,40)));near(output(doc,e)[0].points[0][0],120);assert.equal(doc.byId.get(e.id).parameters.Width,200);});
test('explode produces the evaluated geometry and undo restores behavior',()=>{const {doc,e}=fixture([move()]);D.setValues(doc,e.id,{Width:200});P.explode(doc,[e.id]);near(doc.entities[0].points[0][0],100);assert.equal(doc.entities[0].type,'LINE');doc.undo();assert.equal(doc.entities[0].type,'INSERT');near(output(doc,e)[0].points[0][0],100);});
test('DXF bakes distinct evaluated variants without mutating native master',()=>{const {doc,b,e}=fixture([move()]);const other=P.insertBlock(doc,b.id,[500,0,0]);D.setValues(doc,e.id,{Width:200});D.setValues(doc,other.id,{Width:300});const before=doc.snapshot(),text=K.Exchange.writeDXF(doc),again=K.Drawing.from(K.Exchange.parseDXF(text).data);assert.equal(doc.snapshot(),before);assert.equal(again.entities.length,2);assert.notEqual(again.entities[0].block,again.entities[1].block);near(P.expand(again,again.entities[0])[0].points[0][0],100);near(P.expand(again,again.entities[1])[0].points[0][0],700);assert.ok(!again.production.blocks.some(b=>b.dynamic));fs.writeFileSync('tests/fixtures/dynamic-variants.dxf',text);});
test('DXF has no invalid NaN true-color for ByBlock entities',()=>{const {doc}=fixture();assert.ok(!K.Exchange.writeDXF(doc).includes('NaN'));});
test('invalid instance data rejects during native import, not first render',()=>{const {doc}=fixture(),saved=doc.serialize();saved.entities[0].parameters={Width:-1};assert.throws(()=>K.Drawing.from(saved));});
for(const [label,modify]of [
 ['unknown parameter',x=>{x.e.parameters={Unknown:1};}],
 ['unknown action',x=>{x.b.dynamic.actions=[{type:'execute',targets:['line']}];}],
 ['missing action target',x=>{x.b.dynamic.actions=[{type:'move',targets:['missing'],x:1}];}],
 ['duplicate action target',x=>{x.b.dynamic.actions=[{type:'move',targets:['line','line'],x:1}];}],
 ['reserved parameter',x=>{x.b.dynamic.parameters[0].name='constructor';}],
 ['unsafe expression',x=>{x.b.dynamic.actions=[{type:'move',targets:['line'],x:'globalThis.alert(1)'}];}],
 ['nonfinite expression',x=>{x.b.dynamic.actions=[{type:'move',targets:['line'],x:'1/0'}];}],
 ['singular scale',x=>{x.b.dynamic.actions=[{type:'scale',targets:['line'],factor:0}];}],
 ['array overflow',x=>{x.b.dynamic.actions=[{type:'array',targets:['line'],columns:100000,rows:2}];}],
 ['fractional array',x=>{x.b.dynamic.actions=[{type:'array',targets:['line'],columns:1.5}];}],
 ['zero rotation axis',x=>{x.b.dynamic.actions=[{type:'rotate',targets:['line'],angle:1,axis:[0,0,0]}];}],
 ['reversed stretch window',x=>{x.b.dynamic.actions=[{type:'stretch',targets:['line'],min:[10,0,0],max:[0,0,0]}];}],
 ['nonboolean flip',x=>{x.b.dynamic.actions=[{type:'flip',targets:['line'],parameter:'Width'}];}],
 ['invalid enum default',x=>{x.b.dynamic.parameters=[{name:'State',type:'enum',default:'bad',values:['good']}];}],
 ['partial visibility states',x=>{x.b.dynamic.parameters=[{name:'State',type:'enum',default:'A',values:['A','B']}];x.b.dynamic.actions=[{type:'visibility',parameter:'State',states:{A:['line']}}];}],
])test('reject '+label+' atomically',()=>{const x=fixture();modify(x);assert.throws(()=>K.Drawing.from(x.doc.serialize()));});

test('render expansion retains member styles and selectable parent identity',()=>{const {doc,b,e}=fixture();b.entities[1].color='#00ff00';const members=[...P.renderEntities(doc)];assert.equal(members.length,2);assert.ok(members.every(m=>m.owner===e.id));assert.deepEqual(members.map(m=>m.e.color),['#ff0000','#00ff00']);});
test('hidden block members disappear from rendering but remain explodable',()=>{const {doc,b,e}=fixture();const hidden=doc.layers.find(l=>l.id!=='0');hidden.visible=false;b.entities[1].layer=hidden.id;doc.changed();assert.equal([...P.renderEntities(doc)].length,1);assert.equal(P.expand(doc,e).length,2);assert.equal(P.expand(doc,e,[],{n:0},true).length,1);});
test('hidden nested insert layer suppresses every visible child',()=>{const {doc,b,e}=fixture();const layer=doc.layers.find(l=>l.id!=='0');layer.visible=false;doc.production.blocks.push({id:'outer',name:'Outer',entities:[{id:'inner',type:'INSERT',block:b.id,matrix:Array.from(M.identity()),layer:layer.id}]});e.block='outer';doc.changed();assert.equal([...P.renderEntities(doc)].length,0);assert.equal(P.expand(doc,e).length,2);});
test('render cache invalidates after instance parameter and visibility edits',()=>{const {doc,e}=fixture([move()]);const first=[...P.renderEntities(doc)][0].e;D.setValues(doc,e.id,{Width:180});const second=[...P.renderEntities(doc)][0].e;assert.notEqual(first,second);near(second.points[0][0],80);doc.transaction('hide',()=>doc.layer('0').visible=false);assert.equal([...P.renderEntities(doc)].length,0);doc.undo();assert.equal([...P.renderEntities(doc)].length,2);});
test('SVG retains block member appearance with distinct element IDs',()=>{const {doc,b}=fixture();b.entities[1].color='#00ff00';const svg=K.Exchange.writeSVG(doc,{monochrome:false});assert.ok(svg.includes('#ff0000'));assert.ok(svg.includes('#00ff00'));const ids=[...svg.matchAll(/<g id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.equal(ids.length,2);});
test('DXF preserves ByBlock semantics through another editor-compatible read',()=>{const {doc}=fixture();const again=K.Drawing.from(K.Exchange.parseDXF(K.Exchange.writeDXF(doc)).data);assert.equal(P.expand(again,again.entities[0])[0].color,'#ff0000');assert.equal(again.production.blocks.find(b=>b.id===again.entities[0].block).entities[0].color,'byblock');});

const failed=results.filter(r=>r.status==='failed').length;fs.mkdirSync('tests/results',{recursive:true});fs.writeFileSync('tests/results/dynamic-blocks-results.json',JSON.stringify({passed:results.length-failed,failed,tests:results},null,2)+'\n');console.log(`${results.length-failed}/${results.length} dynamic checks passed`);process.exitCode=failed?1:0;
