'use strict';
const assert=require('assert/strict'),fs=require('fs');
for(const m of ['math','geometry','model','exchange','production','kernel','constraints','dynamic-blocks','fonts','unicode-bidi','mtext','source-document','productivity'])require('../src/'+m+'.js');
const K=Kestrel,T=K.MText,{M,V}=K.Math,results=[];
const test=(name,fn)=>{try{fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.stack});console.log('FAIL',name,e.stack);}};
const near=(a,b)=>assert(Math.abs(a-b)<1e-6*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const entity=(text='Test',extra={})=>({type:'MTEXT',position:[0,0,0],height:5,width:100,text,...extra});
const comp=(text,extra)=>T.compose(entity(text,extra));
const content=p=>p.paragraphs.flatMap(p=>p.items).filter(i=>i.kind==='text').map(i=>i.text).join('');
test('nested formatting restores parent color and height',()=>{const p=T.parse('a{\\C1;\\H2x;b{\\H2x;c}d}e',{height:5}),i=p.paragraphs[0].items;assert.deepEqual(i.map(x=>x.style.height),[5,10,20,10,5]);assert(!i.at(-1).style.color);});
test('literal escaped braces/backslash and Unicode are distinct',()=>{assert.equal(content(T.parse('\\{A\\} \\\\U+0041 \\U+0042')), '{A} \\U+0041 B');});
test('Unicode surrogate pairs survive parser',()=>assert.equal(content(T.parse('\\U+D83D\\U+DE80')), '🚀'));
test('paragraph and explicit column breaks remain separate',()=>{const p=T.parse('a\\Pb\\Nc');assert.equal(p.paragraphs.length,3);assert.equal(p.paragraphs[2].columnBreak,true);});
test('plain newlines and blank trailing paragraph survive',()=>assert.equal(T.parse('a\r\n\n').paragraphs.length,3));
test('underline overline and strike switches retain run style',()=>{const p=T.parse('\\L\\O\\Kabc\\l\\o\\kdef').paragraphs[0].items;assert(p[0].style.underline&&p[0].style.overline&&p[0].style.strike);assert(!p[1].style.underline);});
test('all stack separators preserve both operands',()=>{for(const divider of ['/', '#', '^']){const i=T.parse('\\S3'+divider+'8;').paragraphs[0].items[0];assert.equal(i.top,'3');assert.equal(i.bottom,'8');assert.equal(i.divider,divider);}});
test('font bold italic tracking and slant controls',()=>{const i=T.parse('\\fLocal.ttf|b1|i1;\\T1.4;\\W0.8;\\Q20;abc').paragraphs[0].items[0];assert.equal(i.style.font,'Local.ttf');assert(i.style.bold&&i.style.italic);assert.equal(i.style.tracking,1.4);assert.equal(i.style.oblique,20);});
test('paragraph indents tabs and alignment controls',()=>{const p=T.parse('\\pxi2,l3,r4,qj,t8,16;abc').paragraphs[0];assert.equal(p.indent,2);assert.equal(p.left,3);assert.equal(p.align,'justify');assert.deepEqual(p.tabs,[8,16]);});
test('fields remain literal and never execute',()=>{const p=T.parse('%<process.exit(99)>%');assert.equal(content(p),'%<process.exit(99)>%');assert(p.warnings.some(x=>x.includes('literal')));});
test('unknown controls and unbalanced groups are reported',()=>{assert(T.parse('a\\Zb}').warnings.length===2);assert(T.parse('{a').warnings.length===1);});
test('bounded formatting nesting rejects hostile input',()=>assert.throws(()=>T.parse('{'.repeat(40)+'a')));
test('oversized raw text rejects before layout',()=>assert.throws(()=>T.parse('a'.repeat(50001))));
test('word wrap creates actual separate baselines',()=>{const c=comp('one two three four',{width:30});assert(c.allLines.length>1);assert(c.runs[1].y>c.runs[0].y);});
test('unbounded width measures actual content',()=>near(comp('abcd',{width:0}).width,13.2));
test('NBSP keeps words together until emergency overflow',()=>{const c=comp('a\\~b c',{width:12});assert.equal(c.runs[0].text,'a\u00a0b');});
test('grapheme-safe emergency wrapping does not split combining marks',()=>{const c=comp('a\u0301'.repeat(20),{width:10});for(const r of c.runs)assert(!r.text.startsWith('\u0301'));});
test('emoji surrogate pairs stay valid through wrapping',()=>{const c=comp('🚀'.repeat(20),{width:20});assert.equal(c.runs.map(r=>r.text).join(''),'🚀'.repeat(20));});
test('CJK characters wrap in bounded columns',()=>assert(comp('漢字测试文本绘图',{width:15}).allLines.length>1));
test('mixed direction resolves numbers separately from RTL words',()=>{const c=comp('שלום 123');assert(c.runs.some(r=>r.text==='123'&&r.direction==='ltr'));assert(c.runs.some(r=>r.text.includes('שלום')&&r.direction==='rtl'));});
test('explicit bidi isolates are not visible glyphs',()=>{const c=comp('abc \u2067שלום\u2069 xyz');assert(!c.runs.some(r=>/[\u2067\u2069]/.test(r.text)));});
test('Arabic logical text reaches the outline shaping run',()=>assert(comp('مرحبا بالعالم').runs.some(r=>r.text==='مرحبا بالعالم'&&r.direction==='rtl')));
for(let a=1;a<=9;a++)test('attachment '+a+' anchors the full rectangle',()=>{const c=comp('ABC',{attachment:a}),p=c.quads[0][0];near(p[0],-((a-1)%3)*c.width/2);near(p[1],Math.floor((a-1)/3)*c.height/2);});
test('exact line spacing does not expand for taller characters',()=>{const a=comp('\\H3x;A\\PB',{spacingStyle:2}),b=comp('\\H3x;A\\PB',{spacingStyle:1});assert(a.height<b.height);});
test('tab stop affects the next run position',()=>{const c=comp('\\pxt4,8;A\tB');near(c.runs[1].x,20);});
test('stacked fractions emit distinct baselines and a divider',()=>{const c=comp('\\S3/8;');assert.equal(c.runs.length,2);assert(c.runs[0].y<c.runs[1].y);assert.equal(c.lines.length,1);});
test('paragraph center justification positions real run',()=>{const c=comp('\\pxqc;AB');near(c.runs[0].x,(100-6.6)/2);});
test('column balancing and reversed flow keep every line',()=>{const c=comp('A\\PB\\PC\\PD',{columns:{count:2,width:40,gutter:7,height:0,autoHeight:true,reverse:true}});assert.equal(c.quads.length,2);assert(c.runs[0].x>=47);assert(c.runs[2].x<47);assert.equal(c.width,87);});
test('column overflow is visible and explicitly reported',()=>assert(comp('A\\PB\\PC',{columns:{count:1,width:40,gutter:0,height:5,autoHeight:false}}).warnings.some(w=>w.includes('overflow'))));
for(const props of [{height:0},{width:-1},{attachment:10},{spacingFactor:6},{spacingStyle:3},{textDirection:'bad'},{drawingDirection:3},{columns:{count:33,width:10}},{textAxisX:[0,0,0]}])test('invalid composition settings reject '+JSON.stringify(props),()=>assert.throws(()=>comp('a',props)));
let d,e;
function fresh(text='Hello {\\C1;world}\\Psecond'){d=new K.Drawing();d.currentLayer='0';d.transaction('fixture',()=>e=d.add(entity(text)));return d;}
test('native project round trip retains raw controls',()=>{fresh();assert.equal(K.Drawing.from(d.serialize()).entities[0].text,e.text);});
test('rich text mutation undo and redo restores original controls',()=>{fresh();const before=e.text;d.transaction('edit',()=>e.text='\\C2;new');d.undo();assert.equal(d.entities[0].text,before);d.redo();assert.equal(d.entities[0].text,'\\C2;new');});
test('native affine shear preserves every text-plane corner',()=>{fresh();const old=T.compose(e,d),m=M.identity();m[4]=.4;m[8]=.2;m[12]=20;const next=T.compose(K.Geo.transform(e,m),d);old.quads[0].forEach((p,i)=>near(V.dist(M.point(m,p),next.quads[0][i]),0));});
test('ordinary move rotate and scale update rich geometry',()=>{fresh();const m=M.multiply(M.translation(30,20,5),M.rotation(.3));d.transaction('move',()=>d.transform([e.id],m));assert.deepEqual(d.entities[0].position,[30,20,5]);d.undo();assert.deepEqual(d.entities[0].position,[0,0,0]);});
test('nonuniform rich text remains native but refuses misleading DXF export',()=>{fresh();d.transaction('scale',()=>d.transform([e.id],M.scale(2,1,1)));assert.throws(()=>K.Exchange.writeDXF(d),/nonuniform/);});
test('DXF contains true MTEXT with raw formatting',()=>{fresh();const text=K.Exchange.writeDXF(d);assert(text.includes('AcDbMText'));const back=K.Drawing.from(K.Exchange.parseDXF(text).data).entities[0];assert.equal(back.type,'MTEXT');assert.equal(back.text,e.text);});
test('long Unicode formatting strings survive chunked DXF',()=>{fresh('Zażółć 🚀 {\\C1;abc} '.repeat(40));const back=K.Exchange.parseDXF(K.Exchange.writeDXF(d)).data.entities[0];assert.equal(back.text,e.text);});
test('binary DXF preserves editable rich text',()=>{fresh();const binary=K.SourceDocument.toBinary(K.Exchange.writeDXF(d));const back=K.Exchange.parseDXF(binary).data.entities[0];assert.equal(back.text,e.text);});
test('background and attachment survive supported DXF round trip',()=>{fresh();e.background={color:'#123456',padding:.5};e.attachment=8;const back=K.Exchange.parseDXF(K.Exchange.writeDXF(d)).data.entities[0];assert.equal(back.background.color,'#123456');near(back.background.padding,.5);assert.equal(back.attachment,8);});
test('source-preserving MTEXT text edit retains opaque data',()=>{fresh();let text=K.Exchange.writeDXF(d);text=text.replace('0\nEOF','0\nSECTION\n2\nOBJECTS\n0\nXRECORD\n5\nCAFE\n100\nAcDbXrecord\n1\n  opaque text  \n0\nENDSEC\n0\nEOF');const source=K.Drawing.from(K.Exchange.parseDXF(text).data);source.transaction('edit',()=>source.entities[0].text='\\C3;Revised');const out=K.SourceDocument.exportPreserved(source);const value=out.bytes?new TextDecoder().decode(out.bytes):typeof out==='string'?out:new TextDecoder().decode(out);assert(value.includes('  opaque text  '));assert.equal(K.Exchange.parseDXF(value).data.entities[0].text,'\\C3;Revised');});
test('SVG escapes text while emitting typography and background',()=>{fresh('<script>alert(1)</script> & \\f|b1;A');e.background={color:'#ffffff'};const svg=K.Exchange.writeSVG(d);assert(svg.includes('&lt;script&gt;'));assert(!svg.includes('<script>'));assert(svg.includes('font-weight="bold"'));assert(svg.includes('<polygon'));});
test('MTEXT in a block stays a composed entity',()=>{fresh();const block=K.Production.defineBlock(d,'Rich',[e.id]);const g=d.geometry(d.entities[0]);assert(g.texts[0].composition);assert.equal(K.Production.expand(d,d.entities[0])[0].type,'MTEXT');});
test('explode creates evaluated text and is undoable',()=>{fresh('A{\\C1;B}\\P\\S3/8;');const ids=T.explode(d,[e.id]);assert(ids.length>=5);assert(!d.entities.some(e=>e.type==='MTEXT'));d.undo();assert.equal(d.entities[0].type,'MTEXT');});
test('missing inline font is reported by dependency checks',()=>{fresh('\\fno-such-font.shx;A');assert(K.Fonts.report(d).some(w=>w.includes('no-such-font')));});
const failed=results.filter(t=>t.status==='failed').length;fs.mkdirSync('tests/results',{recursive:true});fs.writeFileSync('tests/results/mtext-results.json',JSON.stringify({passed:results.length-failed,failed,tests:results},null,2));console.log('RESULT',results.length-failed,'passed;',failed,'failed');process.exitCode=failed?1:0;
