'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
for(const f of ['math','geometry','model','exchange','production','kernel','constraints','dynamic-blocks','fonts','source-archive'])require('../src/'+f+'.js');
const K=global.Kestrel,A=K.SourceArchive,M=K.Math.M,tests=[];
function test(name,fn){try{fn();tests.push({name,status:'passed'});console.log('PASS',name);}catch(e){tests.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e);}}
const load=raw=>K.Drawing.from(K.Exchange.parseDXF(raw,'Archive').data),utf=s=>new TextEncoder().encode(s),same=(a,b)=>assert.deepEqual(Array.from(a),Array.from(b));
function fixture(type='LINE',props={points:[[0,0,0],[10,5,0]]}){const d=new K.Drawing('Archive');d.currentLayer='0';d.add(type,props);return K.Exchange.writeDXF(d);}
function rawRecord(raw,type){return A.scan(raw).records.find(r=>r.type===type&&r.section==='ENTITIES');}
const fixtures=[['LINE',{points:[[0,0,0],[10,5,0]]}],['POINT',{position:[2,3,0]}],['CIRCLE',{center:[0,0,0],radius:10}],['ARC',{center:[3,4,0],radius:7,startAngle:.1,endAngle:2}],['ELLIPSE',{center:[3,4,0],rx:10,ry:4,normal:[0,0,1]}],['POLYLINE',{points:[[0,0,0],[10,0,0],[10,10,0]],closed:true,bulges:[0,.2,0]}],['SPLINE',{controlPoints:[[0,0,0],[5,4,0],[10,0,0]],degree:2}],['TEXT',{position:[1,2,0],text:'Unicode Żółć Ω',height:3}]];
for(const binary of [false,true])for(const[type,props]of fixtures)test((binary?'binary':'ASCII')+' original and source edit '+type,()=>{
 const s=load(fixture(type,props)),input=binary?A.binaryDXF(s):utf(fixture(type,props)),d=load(input);assert(A.evaluate(d).unchanged);same(A.write(d),input);same(A.original(d).bytes,input);
 d.transaction('Translate',()=>d.transform([d.entities[0].id],M.translation(7,2,0)));const plan=A.evaluate(d);assert(plan.canPreserve,plan.issues.join(';'));assert.equal(plan.changes.modified,1);
 const output=A.write(d),after=load(output),e=d.entities[0],f=after.entities[0];assert.equal(e.type,f.type);
 const a=e.points||e.controlPoints||[e.center||e.position],b=f.points||f.controlPoints||[f.center||f.position];for(let i=0;i<a.length;i++)for(let j=0;j<3;j++)assert(Math.abs(a[i][j]-b[i][j])<1e-9);
 d.undo();same(A.write(d),input);d.redo();same(A.write(d),output);
});
test('whitespace, CRLF, BOM and opaque records survive unchanged byte for byte',()=>{
 let raw='\ufeff'+fixture().replaceAll('\n','\r\n').replace('0\r\nEOF','999\r\n leading and trailing comment  \r\n0\r\nEOF');
 const input=utf(raw),d=load(input);same(A.write(d),input);d.transaction('move',()=>d.transform([d.entities[0].id],M.translation(1,0,0)));const output=A.write(d);assert(new TextDecoder().decode(output).includes(' leading and trailing comment  '));assert.equal(output[0],239);
});
test('changed coordinates preserve unknown extended data bytes and insertion before XDATA',()=>{
 const base=fixture(),r=rawRecord(base,'LINE'),extra='1001\nMY_APP\n1000\n  untouched Ω \\literal  \n1040\n123.45678912345\n';const input=utf(base.slice(0,r.end)+extra+base.slice(r.end)),d=load(input);d.transaction('elevate',()=>d.transform([d.entities[0].id],M.translation(0,0,7)));const output=new TextDecoder().decode(A.write(d));assert(output.includes(extra));const record=rawRecord(output,'LINE');assert(record.ordinary.some(t=>t.code===30&&Number(t.value)===7));
});
test('persistent-reactor edits block instead of overwriting application dependencies',()=>{const raw=fixture(),r=rawRecord(raw,'LINE'),data=raw.slice(0,r.end)+'102\n{ACAD_REACTORS\n330\nABC\n102\n}\n'+raw.slice(r.end),d=load(data);d.transaction('move',()=>d.transform([d.entities[0].id],M.translation(1,0,0)));assert(!A.evaluate(d).canPreserve);assert.throws(()=>A.write(d),/reactor/);same(A.original(d).bytes,utf(data));});
test('entity type conversion is blocked but its native edit is not discarded',()=>{const d=load(fixture('CIRCLE',{center:[0,0,0],radius:4}));d.transaction('stretch circle',()=>d.transform([d.entities[0].id],M.scale(2,1,1)));assert.equal(d.entities[0].type,'ELLIPSE');assert(!A.evaluate(d).canPreserve);assert.throws(()=>A.write(d),/Entity-type/);});
test('new simple entities receive unique handles and correct model ownership',()=>{const d=load(fixture());d.transaction('new line',()=>d.add('CIRCLE',{center:[7,8,0],radius:2}));const out=A.write(d),s=A.scan(out),entities=s.records.filter(r=>r.section==='ENTITIES'&&['LINE','CIRCLE'].includes(r.type));assert.equal(entities.length,2);assert.notEqual(entities[0].handle,entities[1].handle);assert.equal(entities[0].ordinary.find(t=>t.code===330).value,entities[1].ordinary.find(t=>t.code===330).value);assert.equal(load(out).entities.length,2);});
test('deleting an unreferenced record leaves the rest of the source unchanged',()=>{const raw=fixture(),d=load(raw),r=rawRecord(raw,'LINE');d.transaction('erase',()=>d.remove([d.entities[0].id]));same(A.write(d),utf(raw.slice(0,r.start)+raw.slice(r.end)));});
test('deleting an externally referenced handle is rejected',()=>{let raw=fixture(),r=rawRecord(raw,'LINE');raw=raw.replace('0\nEOF','0\nSECTION\n2\nOBJECTS\n0\nXRECORD\n5\nABCD\n340\n'+r.handle+'\n0\nENDSEC\n0\nEOF');const d=load(raw);d.transaction('erase',()=>d.remove([d.entities[0].id]));assert.throws(()=>A.write(d),/referenced/);});
test('native save and reopen retain original bytes independently of edits',()=>{const raw=fixture(),d=load(raw);d.transaction('move',()=>d.transform([d.entities[0].id],M.translation(5,0,0)));const data=JSON.parse(JSON.stringify(d.serialize())),again=K.Drawing.from(data);same(A.original(again).bytes,utf(raw));same(A.write(again),A.write(d));});
test('large immutable payload is not duplicated into undo entries',()=>{const raw=fixture().replace('0\nEOF','999\n'+'a'.repeat(600000)+'\n0\nEOF'),d=load(raw);d.transaction('move',()=>d.transform([d.entities[0].id],M.translation(5,0,0)));assert(d.undoStack[0].state.length<10000);assert(d.snapshot().length>600000);d.undo();same(A.original(d).bytes,utf(raw));});
test('failed edits restore both geometry and original source identity',()=>{const d=load(fixture()),before=d.snapshot();assert.throws(()=>d.transaction('failure',()=>{d.entities[0].points[0][0]=99;throw Error('stop');}));assert.equal(d.snapshot(),before);assert.equal(d.undoStack.length,0);});
test('serialized archive is immutable and cannot corrupt the source',()=>{const d=load(fixture()),a=d.serialize().sourceArchive;assert.throws(()=>a.bytes='bad',TypeError);assert.throws(()=>a.baseline.entities[0].points[0][0]=77,TypeError);assert(A.evaluate(d).unchanged);});
test('internal history references cannot be loaded as native files',()=>{const d=load(fixture());assert.throws(()=>K.Drawing.from(d.serialize(true)),/Internal source/);});
test('malformed archive and wrong byte counts reject before opening',()=>{const d=load(fixture());for(const change of [a=>a.bytes='!bad',a=>a.byteLength++,a=>a.schema=99]){const data=JSON.parse(d.snapshot());change(data.sourceArchive);assert.throws(()=>K.Drawing.from(data));}});
test('unit/layer/definition changes produce explicit preservation blockers',()=>{for(const fn of [d=>d.units='in',d=>d.layers[0].name='renamed',d=>d.production.ucs.origin=[7,8,0]]){const d=load(fixture());d.transaction('metadata',()=>fn(d));assert(!A.evaluate(d).canPreserve);}});
test('synthetic opaque DWG backup is original-only, not a DWG codec',()=>{const d=new K.Drawing('Opaque'),data=d.serialize(),raw=utf('AC1032\0synthetic opaque bytes');A.withOriginal(data,raw,'opaque.dwg');const a=K.Drawing.from(data);same(A.original(a).bytes,raw);a.transaction('add',()=>a.add('POINT',{position:[0,0,0]}));assert(!A.evaluate(a).canPreserve);same(A.original(a).bytes,raw);});
test('original DWG backup survives the supported converted-DXF view',()=>{const data=K.Exchange.parseDXF(fixture()).data,raw=utf('AC1032\0synthetic backup');A.withOriginal(data,raw,'original.dwg');const d=K.Drawing.from(data);same(A.original(d).bytes,raw);assert(A.evaluate(d).unchanged);assert(A.write(d).length>raw.length);});
test('binary integer, boolean, floating and chunk types decode without coercion',()=>{const prefix=utf('AutoCAD Binary DXF\r\n\x1a\0'),tags=[[0,'SECTION'],[2,'ENTITIES'],[0,'POINT'],[5,'A'],[10,'1.2345678912345'],[20,'2'],[30,'0'],[160,'9223372036854775807'],[290,'1'],[1070,'-32768'],[1071,'-2147483648'],[310,'00FFAA'],[0,'ENDSEC'],[0,'EOF']];const buffers=[prefix,...tags.map(([c,v])=>A.pairBytes(c,v,{binary:true,wide:true}))],all=Buffer.concat(buffers),s=A.scanBinary(all);assert.equal(s.tags.find(t=>t.code===160).value,'9223372036854775807');assert.equal(s.tags.find(t=>t.code===310).value,'00FFAA');});
test('legacy R12 binary one-byte and extended group codes decode',()=>{const tags=[[0,'SECTION'],[2,'ENTITIES'],[0,'LINE'],[5,'A'],[10,'0'],[20,'0'],[11,'10'],[21,'0'],[1001,'APP'],[1071,'321'],[0,'ENDSEC'],[0,'EOF']],raw=Buffer.concat([utf('AutoCAD Binary DXF\r\n\x1a\0'),...tags.map(([c,v])=>A.pairBytes(c,v,{binary:true,wide:false}))]);const d=load(raw);same(A.write(d),raw);d.transaction('translate',()=>d.transform([d.entities[0].id],M.translation(2,0,0)));assert.equal(load(A.write(d)).entities[0].points[0][0],2);});
test('truncated binary values and invalid booleans reject',()=>{const raw=A.binaryDXF(load(fixture()));assert.throws(()=>A.scanBinary(raw.slice(0,-1)),/Truncated/);assert.throws(()=>A.pairBytes(290,'2',{binary:true,wide:true}),/range/);assert.throws(()=>A.pairBytes(310,'XYZ',{binary:true,wide:true}),/chunk/);});
test('sub-nanometer edits are not rounded away during source patching',()=>{const d=load(fixture());d.transaction('tiny change',()=>d.entities[0].points[0][0]=1e-12);const e=load(A.write(d)).entities[0];assert.equal(e.points[0][0],1e-12);});
test('generation bits, linetype-generation flag and hidden state survive independent edits',()=>{
 let raw=fixture('POLYLINE',{points:[[0,0,0],[10,0,0],[10,10,0]],closed:true}),r=rawRecord(raw,'LWPOLYLINE');const flag=r.tags.find(t=>t.code===70);raw=raw.slice(0,flag.start)+'70\n129\n'+raw.slice(flag.end);const d=load(raw);d.transaction('open',()=>{d.entities[0].closed=false;d.entities[0].hidden=true;});const out=A.write(d),record=rawRecord(out,'LWPOLYLINE');assert.equal(Number(record.tags.find(t=>t.code===70).value),128);assert.equal(load(out).entities[0].hidden,true);
});
test('ACI-to-ByLayer color edit updates the actual source color code',()=>{let raw=fixture(),r=rawRecord(raw,'LINE');raw=raw.slice(0,r.end)+'62\n1\n'+raw.slice(r.end);const d=load(raw);d.transaction('bylayer',()=>d.entities[0].color='bylayer');const record=rawRecord(A.write(d),'LINE');assert.equal(record.tags.find(t=>t.code===62).value,'256');assert.equal(load(A.write(d)).entities[0].color,'bylayer');});
test('source-preserving linetype edits require an existing definition',()=>{const d=load(fixture());d.transaction('style',()=>d.entities[0].linetype='MissingCustom');assert.throws(()=>A.write(d),/not defined/);d.undo();d.transaction('style',()=>d.entities[0].linetype='Dashed');assert.equal(load(A.write(d)).entities[0].linetype,'Dashed');});
test('single-line text edits preserve leading and trailing spaces',()=>{const d=load(fixture('TEXT',{position:[0,0,0],text:'  initial  ',height:3}));assert.equal(d.entities[0].text,'  initial  ');d.transaction('text',()=>d.entities[0].text='  new Żółć  ');assert.equal(load(A.write(d)).entities[0].text,'  new Żółć  ');});
test('ambiguous source handles block edits while keeping the original available',()=>{const base=fixture(),r=rawRecord(base,'LINE'),raw=base.slice(0,r.end)+base.slice(r.start,r.end)+base.slice(r.end),d=load(raw);d.transaction('edit',()=>d.entities[0].points[0][0]=2);assert.throws(()=>A.write(d),/unique/);same(A.original(d).bytes,utf(raw));});
test('vertex count changes are rejected without losing the native edit',()=>{const d=load(fixture('POLYLINE',{points:[[0,0,0],[10,0,0]],closed:false}));d.transaction('vertex',()=>d.entities[0].points.push([20,0,0]));assert.throws(()=>A.write(d),/vertex count/);assert.equal(d.entities[0].points.length,3);});
test('64-bit integers reject overflow rather than wrapping',()=>{for(const n of ['9223372036854775808','-9223372036854775809'])assert.throws(()=>A.pairBytes(160,n,{binary:true,wide:true}),/range/);});
test('archive baseline uses normal native geometry validation',()=>{const data=JSON.parse(load(fixture()).snapshot());data.sourceArchive.baseline.entities[0].points[0][0]='NaN';assert.throws(()=>K.Drawing.from(data),/coordinate/i);});
test('Unicode block definitions retain distinct names during converted round trips',()=>{const d=new K.Drawing();d.currentLayer='0';for(const name of ['Żółć','Łódź']){const e=d.add('LINE',{points:[[0,0,0],[10,0,0]]});K.Production.defineBlock(d,name,[e.id]);}const again=load(K.Exchange.writeDXF(d));assert.deepEqual(again.production.blocks.map(b=>b.name).sort(),['Łódź','Żółć'].sort());});
fs.mkdirSync('tests/results',{recursive:true});const failed=tests.filter(t=>t.status==='failed').length;fs.writeFileSync('tests/results/source-archive-results.json',JSON.stringify({passed:tests.length-failed,failed,tests},null,2));console.log('Archive:',tests.length-failed,'passed;',failed,'failed');process.exitCode=Number(!!failed);
