'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
for(const file of ['math','geometry','model','exchange','production','kernel','constraints','spatial-constraints'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../src',file+'.js'),'utf8'),{filename:file+'.js'});
const K=globalThis.Kestrel,C=K.SpatialConstraints,{V,M}=K.Math,results=[];
function test(name,fn){try{fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e.stack);}}
function near(a,b,t=1e-6){if(Array.isArray(a)){assert.equal(a.length,b.length);a.forEach((v,i)=>near(v,b[i],t));}else assert(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);}
function doc(){const d=new K.Drawing();d.currentLayer='0';return d;}
const pt=(d,p)=>d.add('POINT',{position:p}),line=(d,a,b)=>d.add('LINE',{points:[a,b]});
const ref=(e,point='start')=>({entity:e.id,...(C.RIGID.has(e.type)?{local:[0,0,0]}:{point:e.type==='POINT'?'position':point})});
const datum=(p=[0,0,0],axis=[0,0,1],xaxis=[1,0,0])=>({world:p,axis,xaxis});
const fixed=(d,e)=>C.add(d,{type:'fixed-entity',a:ref(e)});
const pos=(d,e)=>d.byId.get(e.id).position;
function put(d,constraints,parameters=[]){d.transaction('Define spatial design',()=>{const s=C.state(d,true);s.parameters=parameters;s.constraints=constraints.map((c,i)=>({id:'test'+i,...c}));});}
function box(d,origin=[0,0,0]){return d.add(K.Geo.box(origin,10,20,30));}
function bodyRef(e,p=[0,0,0],axis=[0,0,1],xaxis=[1,0,0]){return {entity:e.id,local:p,axis,xaxis};}
const at=(d,e,p=[0,0,0])=>M.point(C.frame(d.byId.get(e.id)),p);
test('true 3D distance changes world Z rather than projecting to XY',()=>{const d=doc(),p=pt(d,[0,0,5]);C.add(d,{type:'distance',a:ref(p),b:datum(),value:20});near(V.len(pos(d,p)),20);near(pos(d,p),[0,0,20]);});
for(const [kind,i]of [['distance-x',0],['distance-y',1],['distance-z',2]])test(kind+' signed dimensional constraint',()=>{const d=doc(),p=pt(d,[3,4,5]);C.add(d,{type:kind,a:datum(),b:ref(p),value:-12});near(pos(d,p)[i],-12);});
test('coincidence removes three independent free-space DOFs',()=>{const d=doc(),p=pt(d,[2,3,4]);C.add(d,{type:'coincident',a:ref(p),b:datum([10,20,30])});near(pos(d,p),[10,20,30]);assert.equal(d.spatialReport.degreesOfFreedom,0);assert.equal(d.spatialReport.rank,3);});
test('fixed point is captured and held through ordinary edits',()=>{const d=doc(),p=pt(d,[7,8,9]);C.add(d,{type:'fixed-point',a:ref(p)});d.transaction('move',()=>d.transform([p.id],M.translation(20,3,4)));near(pos(d,p),[7,8,9]);});
test('fixed flexible entity eliminates coordinates without losing world Z',()=>{const d=doc(),e=line(d,[1,2,3],[4,5,6]);fixed(d,e);d.transaction('move',()=>d.transform([e.id],M.translation(5,5,5)));near(d.byId.get(e.id).points,[[1,2,3],[4,5,6]]);assert.equal(d.spatialReport.variables,0);});
test('a positive distance from initially coincident points selects a finite branch',()=>{const d=doc(),p=pt(d,[0,0,0]);C.add(d,{type:'distance',a:ref(p),b:datum(),value:5});near(V.len(pos(d,p)),5);});
test('distance zero converges to coincidence without NaN',()=>{const d=doc(),p=pt(d,[3,4,5]);C.add(d,{type:'distance',a:ref(p),b:datum(),value:0});near(pos(d,p),[0,0,0]);});
test('arbitrarily oriented point-to-plane distance is signed',()=>{const d=doc(),p=pt(d,[1,2,3]),n=V.norm([1,2,3]);C.add(d,{type:'point-plane',a:ref(p),b:datum([5,6,7],n),value:-4});near(V.dot(V.sub(pos(d,p),[5,6,7]),n),-4);});
test('point on a spatial line removes two DOFs',()=>{const d=doc(),p=pt(d,[10,3,4]);C.add(d,{type:'point-on-line',a:ref(p),b:datum([2,0,0],[0,0,1])});near(pos(d,p).slice(0,2),[2,0]);assert.equal(d.spatialReport.degreesOfFreedom,1);});
test('3D line angle is not a view-plane angle',()=>{const d=doc(),e=line(d,[0,0,0],[2,2,4]);C.add(d,{type:'fixed-point',a:ref(e)});C.add(d,{type:'angle',a:ref(e),b:datum(),value:45});const p=d.byId.get(e.id).points;near(V.dot(V.norm(V.sub(p[1],p[0])),[0,0,1]),Math.SQRT1_2);});
for(const [type,target]of [['same-direction',1],['opposed',-1],['parallel',1],['perpendicular',0]])test(type+' works in free space',()=>{const d=doc(),e=line(d,[0,0,0],[2,3,4]);C.add(d,{type:'fixed-point',a:ref(e)});C.add(d,{type,a:ref(e),b:datum()});const ps=d.byId.get(e.id).points,cos=V.dot(V.norm(V.sub(ps[1],ps[0])),[0,0,1]);near(type==='parallel'?Math.abs(cos):cos,target);});
for(const angle of [0,180])test('angle '+angle+' has nonsingular endpoint formulation',()=>{const d=doc(),e=line(d,[0,0,0],[2,3,4]);C.add(d,{type:'angle',a:ref(e),b:datum(),value:angle});near(V.dot(V.norm(V.sub(...d.byId.get(e.id).points.slice().reverse())),[0,0,1]),angle===0?1:-1);});
test('equal length uses full 3D length',()=>{const d=doc(),a=line(d,[0,0,0],[3,4,12]),b=line(d,[20,0,0],[20,0,5]);fixed(d,a);C.add(d,{type:'equal-length',a:ref(a),b:ref(b)});near(V.dist(...d.byId.get(b.id).points),13);});
test('length ratio preserves a fixed reference',()=>{const d=doc(),a=line(d,[0,0,0],[0,0,5]),b=line(d,[10,0,0],[10,0,7]);fixed(d,a);C.add(d,{type:'length-ratio',a:ref(b),b:ref(a),value:3});near(V.dist(...d.byId.get(b.id).points),15);});
test('midpoint works on a spatial segment',()=>{const d=doc(),a=line(d,[1,2,3],[7,8,9]),p=pt(d,[0,0,0]);fixed(d,a);C.add(d,{type:'midpoint',a:ref(p),b:ref(a)});near(pos(d,p),[4,5,6]);});
test('symmetry reflects through an arbitrary world plane',()=>{const d=doc(),p=pt(d,[1,2,3]),q=pt(d,[0,0,0]),n=V.norm([1,1,0]);fixed(d,p);C.add(d,{type:'symmetric',a:ref(p),b:ref(q),c:datum([0,0,0],n)});near(pos(d,q),[-2,-1,3]);});
test('fully constrained nonplanar tetrahedron retains all six true edge lengths',()=>{const d=doc(),p=pt(d,[2,2,6]);put(d,[{type:'distance',a:ref(p),b:datum(),value:5},{type:'distance',a:ref(p),b:datum([3,0,0]),value:Math.sqrt(34)},{type:'distance',a:ref(p),b:datum([0,4,0]),value:Math.sqrt(41)}]);near(pos(d,p),[0,0,5]);assert.equal(d.spatialReport.degreesOfFreedom,0);});
test('a rigid body has six participating pose variables',()=>{const d=doc(),e=box(d);C.add(d,{type:'coincident',a:bodyRef(e,[5,10,15]),b:datum([30,40,50])});assert.equal(d.spatialReport.variables,6);assert.equal(d.spatialReport.degreesOfFreedom,3);near(at(d,e,[5,10,15]),[30,40,50]);near(K.Geo.volume(d.byId.get(e.id)),6000);});
test('fastened frame fixes all six rigid-body freedoms',()=>{const d=doc(),e=box(d);C.add(d,{type:'fastened',a:bodyRef(e),b:datum([10,20,30],[1,0,0],[0,1,0])});near(at(d,e),[10,20,30]);near(V.norm(M.point(C.frame(d.byId.get(e.id)),[0,0,1],0)),[1,0,0]);assert.equal(d.spatialReport.degreesOfFreedom,0);near(K.Geo.volume(d.byId.get(e.id)),6000);});
test('hinge retains exactly one rotational freedom',()=>{const d=doc(),e=box(d);C.add(d,{type:'hinge',a:bodyRef(e),b:datum([5,0,10],[1,0,0])});assert.equal(d.spatialReport.degreesOfFreedom,1);near(at(d,e),[5,0,10]);});
test('slider retains exactly one translational freedom',()=>{const d=doc(),e=box(d);C.add(d,{type:'slider',a:bodyRef(e),b:datum([5,7,0])});assert.equal(d.spatialReport.degreesOfFreedom,1);near(at(d,e).slice(0,2),[5,7]);});
test('coaxial mate permits axial slide and rotation',()=>{const d=doc(),e=box(d);C.add(d,{type:'coaxial',a:bodyRef(e),b:datum([5,7,0],[0,0,1])});assert.equal(d.spatialReport.degreesOfFreedom,2);near(at(d,e).slice(0,2),[5,7]);});
test('opposed plane mate leaves two translations and one spin',()=>{const d=doc(),e=box(d);C.add(d,{type:'plane-mate',a:bodyRef(e,[5,10,30]),b:datum([0,0,40],[0,0,-1]),value:2});assert.equal(d.spatialReport.degreesOfFreedom,3);near(at(d,e,[5,10,30])[2],38);});
test('two rigid bodies retain independent geometry while solving a hinge',()=>{const d=doc(),a=box(d),b=box(d);fixed(d,a);C.add(d,{type:'hinge',a:bodyRef(b),b:bodyRef(a,[5,10,30])});near(at(d,b),[5,10,30]);near(K.Geo.volume(d.byId.get(a.id)),6000);near(K.Geo.volume(d.byId.get(b.id)),6000);});
test('rigid fixed pose survives an ordinary move and rotation',()=>{const d=doc(),e=box(d);fixed(d,e);d.transaction('move body',()=>d.transform([e.id],M.multiply(M.translation(12,13,14),M.rotation(.3))));near(d.byId.get(e.id).vertices,e.vertices);});
test('mesh-vertex anchors move rigidly with the whole body',()=>{const d=doc(),e=box(d);C.add(d,{type:'coincident',a:{entity:e.id,vertex:6},b:datum([50,50,50])});near(d.byId.get(e.id).vertices[6],[50,50,50]);near(K.Geo.volume(d.byId.get(e.id)),6000);});
test('INSERT constraints preserve reusable definition geometry',()=>{const d=doc(),e=line(d,[0,0,0],[10,0,0]),b=K.Production.defineBlock(d,'Part',[e.id]),insert=d.entities[0];const original=JSON.stringify(b.entities);C.add(d,{type:'fastened',a:bodyRef(insert),b:datum([50,60,70])});near(M.point(d.byId.get(insert.id).matrix,[0,0,0]),[50,60,70]);assert.equal(JSON.stringify(d.production.blocks[0].entities),original);assert(d.geometry(d.byId.get(insert.id)).segments.length);});
test('named expressions drive simultaneous true 3D distances',()=>{const d=doc(),p=pt(d,[5,6,7]);put(d,[{type:'distance-x',a:datum(),b:ref(p),value:'Width'},{type:'distance-y',a:datum(),b:ref(p),value:'Height'},{type:'distance-z',a:datum(),b:ref(p),value:'Width / 2'}],[{name:'Width',expression:'20'},{name:'Height',expression:'Width*1.5'}]);near(pos(d,p),[20,30,10]);d.transaction('Resize',()=>C.state(d).parameters[0].expression='40');near(pos(d,p),[40,60,20]);});
test('failed dimensional edit rolls back graph, geometry, dirty and undo counts',()=>{const d=doc(),p=pt(d,[0,0,0]);C.add(d,{type:'coincident',a:ref(p),b:datum()});const snap=d.snapshot(),n=d.undoStack.length;assert.throws(()=>C.add(d,{type:'distance',a:ref(p),b:datum(),value:20}),/rolled back/);assert.equal(d.snapshot(),snap);assert.equal(d.undoStack.length,n);});
test('redundant consistent equations are reported separately',()=>{const d=doc(),p=pt(d,[3,4,5]);put(d,[{type:'coincident',a:ref(p),b:datum()},{type:'coincident',a:ref(p),b:datum()}]);assert.equal(d.spatialReport.redundantEquations,3);});
test('diagnostic solve without applying never modifies coordinates',()=>{const d=doc(),p=pt(d,[4,5,6]);const s=C.state(d,true);s.constraints=[{id:'probe',type:'coincident',a:ref(p),b:datum()}];const before=JSON.stringify(d.entities);assert(C.solve(d,{apply:false}).converged);assert.equal(JSON.stringify(d.entities),before);});
test('locked geometry is not moved to satisfy a constraint',()=>{const d=doc(),p=pt(d,[1,2,3]);d.layers[0].locked=true;const snap=d.snapshot();assert.throws(()=>C.add(d,{type:'coincident',a:ref(p),b:datum()}),/rolled back/);assert.equal(d.snapshot(),snap);});
test('suppression releases geometry while preserving equations',()=>{const d=doc(),p=pt(d,[1,2,3]);C.add(d,{type:'coincident',a:ref(p),b:datum()});d.transaction('Suppress',()=>C.state(d).constraints[0].suppressed=true);d.transaction('Move',()=>d.transform([p.id],M.translation(5,6,7)));near(pos(d,p),[5,6,7]);});
test('disabled spatial system can be reenabled transactionally',()=>{const d=doc(),p=pt(d,[0,0,0]);C.add(d,{type:'coincident',a:ref(p),b:datum()});d.transaction('Disable',()=>C.state(d).enabled=false);d.transaction('Move',()=>d.transform([p.id],M.translation(5,6,7)));d.transaction('Enable',()=>C.state(d).enabled=true);near(pos(d,p),[0,0,0]);});
test('undo redo restores graph, rigid pose, coordinates and identity',()=>{const d=doc(),e=box(d),before=d.snapshot();C.add(d,{type:'fastened',a:bodyRef(e),b:datum([5,6,7])});const after=d.snapshot();d.undo();assert.equal(d.snapshot(),before);d.redo();assert.equal(d.snapshot(),after);});
test('native save load preserves constraint schema and rigid frames exactly',()=>{const d=doc(),e=box(d);C.add(d,{type:'hinge',a:bodyRef(e),b:datum([8,9,10])});assert.equal(K.Drawing.from(d.serialize()).snapshot(),d.snapshot());});
test('deleting referenced geometry prunes its constraints and undo restores them',()=>{const d=doc(),p=pt(d,[1,2,3]);C.add(d,{type:'coincident',a:ref(p),b:datum()});d.transaction('Delete',()=>d.remove([p.id]));assert.equal(C.state(d).constraints.length,0);d.undo();assert.equal(C.state(d).constraints.length,1);});
test('physical units scale flexible targets and world datums',()=>{const d=doc(),p=pt(d,[25.4,0,0]);C.add(d,{type:'fixed-point',a:ref(p)});d.transaction('Units',()=>{C.convertUnits(d,'in',1/25.4,true);d.transform([p.id],M.scale(1/25.4));d.units='in';});near(pos(d,p),[1,0,0]);});
test('physical units preserve driving dimensions and rigid local datums',()=>{const d=doc(),e=box(d);C.add(d,{type:'fastened',a:bodyRef(e),b:datum([25.4,50.8,76.2])});d.transaction('Units',()=>{C.convertUnits(d,'in',1/25.4,true);d.transform([e.id],M.scale(1/25.4));d.units='in';});near(at(d,e),[1,2,3]);near(K.Geo.volume(d.byId.get(e.id)),6000/25.4**3);});
test('metadata-only unit edit keeps numerical expression meaning',()=>{const d=doc(),p=pt(d,[0,0,1]);C.add(d,{type:'distance-z',a:datum(),b:ref(p),value:20});d.transaction('Units',()=>{C.convertUnits(d,'in',1,false);d.units='in';});near(pos(d,p),[0,0,20]);});
test('large world coordinates use camera-independent normalized residuals',()=>{const d=doc(),p=pt(d,[1e9+10,-1e9,1e9]);C.add(d,{type:'coincident',a:ref(p),b:datum([1e9,-1e9,1e9+20])});near(V.dist(pos(d,p),[1e9,-1e9,1e9+20]),0,1e-5);});
function invalid(label,change){test('reject '+label+' atomically',()=>{const d=doc(),p=pt(d,[1,2,3]);const before=d.snapshot();assert.throws(()=>C.add(d,change(p)));assert.equal(d.snapshot(),before);});}
invalid('unknown relation',p=>({type:'arbitrary-code',a:ref(p)}));
invalid('missing entity',p=>({type:'coincident',a:{entity:'missing'},b:datum()}));
invalid('ambiguous datum',p=>({type:'coincident',a:{entity:p.id,world:[0,0,0]},b:datum()}));
invalid('zero axis',p=>({type:'point-plane',a:ref(p),b:datum([0,0,0],[0,0,0])}));
invalid('nonfinite point',p=>({type:'coincident',a:ref(p),b:datum([Infinity,0,0])}));
invalid('negative distance',p=>({type:'distance',a:ref(p),b:datum(),value:-1}));
invalid('angle outside 0..180',p=>({type:'angle',a:ref(p),b:datum(),value:361}));
invalid('zero ratio',p=>({type:'length-ratio',a:ref(p),b:datum(),value:0}));
invalid('unsafe expression',p=>({type:'distance',a:ref(p),b:datum(),value:'globalThis.alert(1)'}));
invalid('missing parameter',p=>({type:'distance',a:ref(p),b:datum(),value:'Missing'}));
invalid('wrong fixed coordinates',p=>({type:'fixed-entity',a:ref(p),target:[0,0]}));
invalid('world datum length',p=>({type:'equal-length',a:ref(p),b:datum()}));
test('reject overlarge free-variable system before dense allocation',()=>{const d=doc(),points=Array.from({length:65},(_,i)=>pt(d,[i,0,0]));assert.throws(()=>put(d,points.map(p=>({type:'coincident',a:ref(p),b:datum()}))),/192/);});
test('reject competing planar and spatial drivers on one free entity',()=>{const d=doc(),e=line(d,[0,0,0],[10,0,0]);K.Constraints.add(d,{type:'horizontal',a:ref(e)});assert.throws(()=>C.add(d,{type:'distance',a:ref(e),b:ref(e,'end'),value:10}),/both planar and spatial/);});
test('planar and spatial systems coexist on disjoint geometry',()=>{const d=doc(),e=line(d,[0,0,0],[10,0,0]),p=pt(d,[0,0,8]);K.Constraints.add(d,{type:'horizontal',a:ref(e)});C.add(d,{type:'distance-z',a:datum(),b:ref(p),value:20});near(pos(d,p),[0,0,20]);});
test('bulged flexible polylines reject rather than straighten silently',()=>{const d=doc(),e=d.add('POLYLINE',{points:[[0,0,0],[10,0,0]],bulges:[1,0]});assert.throws(()=>C.add(d,{type:'fixed-point',a:ref(e)}),/straight/);});
test('singular saved body frame rejects on native load',()=>{const d=doc(),e=box(d);fixed(d,e);const data=d.serialize();data.entities[0].constraintFrame=Array(16).fill(0);assert.throws(()=>K.Drawing.from(data),/frame/);});
test('reference vertex outside topology rejects',()=>{const d=doc(),e=box(d);assert.throws(()=>C.add(d,{type:'coincident',a:{entity:e.id,vertex:999},b:datum()}),/vertex/);});
test('parameter dependency cycle rejects before solver mutation',()=>{const d=doc(),p=pt(d,[1,2,3]);assert.throws(()=>put(d,[{type:'distance',a:ref(p),b:datum(),value:'A'}],[{name:'A',expression:'B'},{name:'B',expression:'A'}]),/cycle/);});
test('solver iteration failure never partially applies geometry',()=>{const d=doc(),p=pt(d,[1,2,3]);C.state(d,true).constraints=[{id:'c',type:'coincident',a:ref(p),b:datum()}];const snap=d.snapshot();assert(!C.solve(d,{maxIterations:0}).converged);assert.equal(d.snapshot(),snap);});

function copy(d,to,m=M.identity()){
 const data=d.serialize(),ids=new Map();to.transaction('Paste spatial design',()=>{for(const e of data.entities){const t=K.Geo.transform(e,m),id=K.uid();ids.set(e.id,id);t.id=id;to.add(t);}to.operationWarnings=C.copyInto(to,data,ids,m);});return ids;
}
test('clipboard transfers complete flexible 3D equations with translation',()=>{const d=doc(),p=pt(d,[0,0,3]);C.add(d,{type:'distance-z',a:datum(),b:ref(p),value:20});const to=doc(),ids=copy(d,to,M.translation(10,20,30));near(to.byId.get(ids.get(p.id)).position,[10,20,50]);assert.equal(C.state(to).constraints.length,1);});
test('clipboard rotates implicit signed coordinate axes instead of resnapping to world XY',()=>{const d=doc(),p=pt(d,[0,0,3]);C.add(d,{type:'distance-z',a:datum(),b:ref(p),value:20});const to=doc(),m=M.rotation(Math.PI/2,[1,0,0]),ids=copy(d,to,m);near(to.byId.get(ids.get(p.id)).position,[0,-20,0]);});
test('clipboard body frame and world mates transform together',()=>{const d=doc(),b=box(d);C.add(d,{type:'fastened',a:bodyRef(b),b:datum([5,6,7])});const to=doc(),m=M.multiply(M.translation(10,20,30),M.rotation(.7,[1,2,3])),ids=copy(d,to,m);near(M.point(C.frame(to.byId.get(ids.get(b.id))),[0,0,0]),M.point(m,[5,6,7]));assert.equal(to.spatialReport.degreesOfFreedom,0);});
test('clipboard scales explicit fixed bodies without losing pose',()=>{const d=doc(),b=box(d);fixed(d,b);const to=doc(),ids=copy(d,to,M.scale(2));near(K.Geo.volume(to.byId.get(ids.get(b.id))),48000);});
test('cross-unit clipboard preserves physical dimensions',()=>{const d=doc(),p=pt(d,[0,0,1]);C.add(d,{type:'distance-z',a:datum(),b:ref(p),value:25.4});const to=doc();to.units='in';const ids=copy(d,to,M.scale(1/25.4));near(to.byId.get(ids.get(p.id)).position,[0,0,1]);});
test('clipboard renames colliding dependent parameters',()=>{const d=doc(),p=pt(d,[0,0,1]);put(d,[{type:'distance-z',a:datum(),b:ref(p),value:'Height'}],[{name:'Width',expression:'10'},{name:'Height',expression:'Width*2'}]);const to=doc();C.state(to,true).parameters=[{name:'Width',expression:'99'}];copy(d,to);near(to.entities[0].position,[0,0,20]);assert(C.state(to).parameters.some(p=>p.name==='Width_copy1'));assert(C.state(to).parameters.some(p=>String(p.expression).includes('Width_copy1')));});
test('clipboard warns and omits external references rather than attaching to wrong IDs',()=>{const d=doc(),p=pt(d,[0,0,0]),q=pt(d,[0,0,5]);C.add(d,{type:'distance',a:ref(p),b:ref(q),value:10});const to=doc(),id=K.uid(),data=d.serialize();to.add({...K.clone(d.byId.get(p.id)),id});const warnings=C.copyInto(to,data,new Map([[p.id,id]]),M.identity());assert(warnings.length);assert(!C.state(to));});
test('clipboard nonuniform transform omits equations with an explicit warning',()=>{const d=doc(),p=pt(d,[0,0,1]);C.add(d,{type:'distance-z',a:datum(),b:ref(p),value:10});const to=doc();copy(d,to,M.scale(2,3,4));assert(to.operationWarnings.some(w=>w.includes('Nonuniform')));assert(!C.state(to));});
test('disconnected angular singularity is solved after a different component moves',()=>{const d=doc(),e=line(d,[0,0,0],[0,0,10]),p=pt(d,[5,6,7]);put(d,[{type:'angle',a:ref(e),b:datum(),value:60},{type:'coincident',a:ref(p),b:datum([5,6,20])}]);const q=d.byId.get(e.id).points;near(V.dot(V.norm(V.sub(q[1],q[0])),[0,0,1]),.5);near(pos(d,p),[5,6,20]);});
test('ordinary nonuniform body edit remains affine while rigid pose solving preserves its shape',()=>{const d=doc(),e=box(d);C.add(d,{type:'coincident',a:bodyRef(e,[5,10,15]),b:datum([5,10,15])});d.transaction('Scale shape',()=>d.transform([e.id],M.scale(2,3,4)));near(at(d,e,[5,10,15]),[5,10,15]);near(K.Geo.volume(d.byId.get(e.id)),144000);});
test('suppressed spatial drivers do not block the planar solver',()=>{const d=doc(),e=line(d,[0,0,0],[10,0,0]);C.add(d,{type:'distance',a:ref(e),b:ref(e,'end'),value:10});d.transaction('Suppress spatial',()=>C.state(d).constraints[0].suppressed=true);K.Constraints.add(d,{type:'horizontal',a:ref(e)});assert(d.constraintReport.converged);});
test('collinear frame axes reject an invalid fastened mate',()=>{const d=doc(),b=box(d);assert.throws(()=>C.add(d,{type:'fastened',a:bodyRef(b,[0,0,0],[1,0,0],[1,0,0]),b:datum()}),/independent axes/);});
let failed=results.filter(r=>r.status==='failed').length;fs.mkdirSync(path.join(__dirname,'results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'results/spatial-results.json'),JSON.stringify({passed:results.length-failed,failed,tests:results},null,2));console.log(`${results.length-failed}/${results.length} spatial checks passed`);process.exitCode=failed?1:0;
